//
//  Book.swift
//  Book Club
//
//  Created by RANGA REDDY NUKALA on 25/06/20.
//

import Foundation
struct Book: Identifiable {
    let id = UUID()
    let title: String
    let author: String
    var progress: Double
    var description: String
    var isDone: Bool = false
    var imageName: String { return title }
}

let testData = [
    Book(title: "The Daughter's Tale", author: "Armando Lucas Correa", progress: 0.3, description: "Armando Lucas Correa: Correa, an award-winning journalist, editor, and author, has written two books about families who face incredible circumstances during World War II. With the international bestseller The German Girl on his roster, Correa delivers again with the poignant and heart-wrenching The Daughter’s Tale. Correa’s journalism background lends itself to his novels beautifully; they are well researched, thoroughly investigated, and told with reverence and respect for the subject matter. If you’re a lover of authentic historical fiction, you should definitely pick up Correa’s books"),
    Book(title: "Himself", author: "Jess Kidd", progress: 0.5, description: "Jess Kidd: The award-winning author of Himself, Jess Kidd is a spectacular writer with one foot in the mythical and the other planted firmly in reality. Kidd creates remarkable characters and real-life settings, and then makes them magical. Her upcoming novel, Things in Jars, is a mesmerizing gothic mystery that follows detective Bridie Devine as she investigates the kidnapping of a London society man’s secret daughter—a girl who is rumored to have supernatural powers. Kidd expertly uses her cast of characters to create and solve the mystery, and her books are ones you don’t want to miss."),
    Book(title: "Goergeous Lies", author: "Martha McPhee", progress: 0.2, description: "Martha McPhee: New York Times bestselling author Martha McPhee’s poetic prose and incredibly aware domestic fiction always delivers. McPhee’s work is expertly crafted and incredibly enticing. Her most notable novel, Gorgeous Lies, is a colorful, quirky story of a dying therapist who tries to make sense of his life and his relationships with his family as his conditions worsen. McPhee’s ability to write about relationships also comes across in her upcoming novel, An Elegant Woman, which follows four generations of women as they fight for their freedom and work toward a better future."),
    Book(title: "The Beautiful Bureaucrat", author: "Helen Phillips", progress: 0.1, description: "Helen Phillips: Dynamic author Helen Phillips is incredibly skilled at weaving together wild fantasy with the mundanity of everyday life. Longlisted for the National Book Award, The Beautiful Bureaucrat tells the story of a woman named Josephine, whose job it is to enter numbers into a mysterious system called The Database. But when her husband disappears, and reappears with no explanation, things quickly turn become bizarre and terrifying. Phillips expertly balances the fear and terror of Josephine’s experience and the exhilarating twists and turns of a political thriller."),
    Book(title: "Eva Luna", author: "Isabel Allende", progress: 0.8, description: "Conceived in an embrace designed to comfort a dying man, born to a servant and raised as a hired hand, Eva Luna learns quickly that she has a talent that belies her humble start: the gift of storytelling. As the years pass and her imprudent nature sends Eva from household to household—from the home of a doctor famed for mummifying the dead to a colorful whorehouse and the care of a beautiful transsexual—it is Eva’s magical imagination that keeps her alive and fuels her ardent encounters with lovers of all kinds. And as her South American homeland teeters on the brink of political chaos, and Eva’s fate is intertwined with guerrilla fighters and revolutionaries, she will find her life’s calling—and the soul mate who will envelop her in a love entirely beyond her mystical inventions."),
    Book(title: "Love Story", author: "Karen Kingsbury", progress: 0.9, description: "When John Baxter is asked to relive his long-ago love story with his wife Elizabeth for his grandson Cole’s heritage school project, he’s not sure he can do it. The sadness might simply be too great—after a storybook romance that lasted almost thirty years, beginning when the two were in college, Elizabeth tragically died of cancer. But John can’t say no to his grandson and in the process of telling his love story, he finally allows his heart and soul to go places they haven’t gone in decades. Back to the breathless first moments, but also to the secret heartbreak that brought John and Elizabeth together.Cole’s report on his grandparents touches the hearts of the entire family—and causes Cole to better understand his own beginning.Whether you’re meeting the Baxter family for the first time or finding them all over again, Love Story will stir your heart and remind you of the generational impact of love and the eternal bond of family."),]


let Buy = [Book(title: "The Dinner List", author: "Rebecca Serle", progress: 0.0, description: "Rebecca Serle: Rebecca Serle is an author and TV writer whose characters move her novels forward seemingly without any help. With perfect pacing and riveting characters, Serle’s adult and YA novels alike deliver poignant heartbreak and exciting triumph. All of her books deliver some truth about the human experience, but in particular, The Dinner List manages to hit all spots on the emotional spectrum. The story follows a woman named Sabrina, who turns up to her 30th birthday to a huge surprise. Prior to the dinner, she made a hypothetical list of the five people, living or dead, that she’d want to have dinner with — and magically, that list comes to life. She’s surrounded by her best friend, three significant people from her past, plus Audrey Hepburn. This tender, thoughtful book shows the way people shape our lives, for better or worse, and what we can learn even when they’re no longer with us."),
           Book (title: "Normal People", author: "Sally Rooney", progress: 0.0, description: "Sally Rooney: Irish author Sally Rooney is an incredibly talented author with unique perspective, well-established characters and thorough understanding of cultural elements that influence who we are. Rooney’s latest novel, Normal People, discusses the relationship between Connell, a handsome and popular boy, and Marianne, an intelligent yet intimidating girl whose family employs Connell’s mother. Rooney follows the pair through their lives and lets us in on the most intimate part of them as they navigate trauma and experience, never quite able to hold on to each other.  You can also find Rooney’s short stories, essays, and poems in places like the Dublin Review and the New Yorker."),
           Book(title: "The Family Upstairs", author: "Lisa Jewell", progress: 0.0, description: "Sally Rooney: Irish author Sally Rooney is an incredibly talented author with unique perspective, well-established characters and thorough understanding of cultural elements that influence who we are. Rooney’s latest novel, Normal People, discusses the relationship between Connell, a handsome and popular boy, and Marianne, an intelligent yet intimidating girl whose family employs Connell’s mother. Rooney follows the pair through their lives and lets us in on the most intimate part of them as they navigate trauma and experience, never quite able to hold on to each other.  You can also find Rooney’s short stories, essays, and poems in places like the Dublin Review and the New Yorker."),
           Book(title: "Kafka on the Shore", author: "Haruki Murakami", progress: 0.0, description: "Haruki Murakami: Japanese writer Haruki Murakami is a prolific bestselling author whose books have been translated into fifty languages and have sold millions of copies outside of Japan. Murakami is noted for his somewhat absurdist humor in his writing, as well as many traditional elements of Japanese literature. Among his many notable novels, Kafka on the Shore follows two distinct plots. In one, a fifteen-year-old boy named Kafka goes on a journey to escape an oedipal curse and find his family. In the other, a cat-finder named Nakata realizes that his path is changing. Murakami’s writing blends so many elements of literature—like humor, magical realism, suspense, and more—and he is truly one of the most groundbreaking writers of our time."),
           Book(title: "Such a Fun Age", author: "Kiley Reid", progress: 0.0, description: "Kiley Reid: Short story writer and Iowa Writers’ Workshop graduate Kiley Reid’s debit novel, Such a Fun Age, is a page-turning drama about race and privilege that centers around a black babysitter named Emira, who one day is accused of kidnapping the white child that she babysits. The child’s mother, Alix, is appalled and wants to help—but Emira, who is young, lost, and wary of the world, is hesitant. Reid expertly explores the social and racial dynamics, and the complicated reality that people face living in a world where we cannot escape the effects of race, privilege, and how they intersect. Reid’s commentary is smart and empathetic and shows her considerable literary talents.")]
